### PR TITLE
Extension to existing functionality

### PR DESCRIPTION
**Pull request by crazylab**
The following changes are made:

- Add **/remove** api which can be used to remove an particular api. When more than one fake-response matches the payload, removes the latest best match.
- Add capability to set requiredHeaders by **/add** endpoint
- responseBody can be a string or a JSON object.
- When more than one fake responses match query params, required headers, payloads, at, breaking tie by timestamp. Returning the latest response.
- Application port and default_routes path made configurable through config.json
- Updated dependencies.
- Change folder structure
- Using builder to create the FakeResponse description.
- More test are added.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by bigodines** [comment]
I am not sure this project is being maintained anymore. I've left yahoo a while ago and lost my admin permissions to merge pull requests :/ given the lack of activity in recent years, I doubt that someone will merge this.

**Comment by crazylab** [comment]
@bigodines Thanks for your response. This is very simple and useful tool. And I'm sure there are people who will get benefit out of this project. It will be helpful if you have any contacts in yahoo who can look at this PR.

**Comment by inerte** [comment]
Hi @crazylab , thanks for your Pull Request! I can see how you've extended the base functionality on fake-server and added some amazing new features (including tests!)

But we can't accept code on the /yahoo Github organization pointing to a npm package we don't control. I noticed you renamed to fake-rest-server and put it as a module on npm. That's awesome! That's what Open Source is for. Feel free to fork and improve on our project, but if we do accept this PR, then the /yahoo Github organization becomes associated with you (or your company) and that might become really messy in terms of ownership, copyright, and support.

I totally support and encourage you to take advantage of our Open Source code, but please let's keep those issues separate.

Thanks!

**Comment by crazylab** [comment]
Hi @inerte I understand your concern and totally agree with you. Publishing it to npm was a later decision I have taken because I get to know this repo is no longer maintained actively. So, i had to take a call rather than relying on someone else. Anyway, thanks for your support.

**Pull request closed without merging**
